src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs

To address #11.
When EventProcessorHost is shutdown (such as when stopping function app or when scaling down), now we do immediately initiate shutdown of all partitions.
That way, when EventProcessorHost finally decides to stop the processors, the work is already done.

implement faster partition shutdown

---

.gitignore
DurableTask.Netherite.sln
test/EventConsumer/Event.cs
test/EventConsumer/EventConsumer.csproj
test/EventConsumer/EventHubTrigger.cs
test/EventConsumer/ReceiverEntity.cs
test/EventConsumer/TestConstants.cs
test/EventConsumer/host.json
test/EventConsumer/local.settings.json
test/EventProducer/EventProducer.csproj
test/EventProducer/Program.cs

Adds a new performance test that consumes events from an event hub, using a trigger, and processes them on an entity.

Add eventhubs consumer test

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/Tracing/ClientTraceHelper.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs

Overrides EventSourceName override to durability provider.
Renames "eventId" fields in EtwSource to "partitionEventId" to avoid name clashes.

Support ETW trace collection on linux

---

src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsConnections.cs

fixes copy-paste bug that caused EventHubs clients to not be closed correctly.

Fix bug in EventHubsConnections.StopAsync

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs

Removes dead code and unnecessary compile switches from the main branch.
We will reintroduce the new implementation for queries later.

remove obsolete code for query support

---

samples/Hello/Hello.csproj
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
test/PerformanceTests/PerformanceTests.csproj

As discussed in #55, this PR implements two mitigations while we wait for fix in Microsoft.NET.Sdk.Functions:
- Add fast fail so package load problem is immediately visible when starting the service, not just during recovery.
- For Hello sample and perf tests, use last functioning version 3.0.3 of Microsoft.NET.Sdk.Functions.

Mitigations for dll load problem

---

src/DurableTask.Netherite/Scaling/ScalingMonitor.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsConnections.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/TaskHubParameters.cs

Validates that existing taskhubs are connected to the original event hubs, and if not, throws exception with informational message.

Validate that a TaskHub always uses the original EventHubs

---

src/DurableTask.Netherite/StorageProviders/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTraceHelper.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/Util/BatchWorker.cs

Several minor improvements to simplify analytics:
- do not trace batchworker work cycles when the batch is empty
- use 'Details' instead of 'Reason' for checkpoint events
- include partition id in EventHubs traces
- use LatencyMs instead of Latency for batch worker tracing
- Do not emit warnings for ReceiverDisconnectedExceptions observed inside EventProcessorHost

ETW tracing improvements

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/PerformanceTests/PerformanceTests.csproj

To pick up latest fixes, in particular azure/durabletask#560.
Also updates Azure.Messaging.EventHubs to 5.5.0.

Update to DurableTask.Core 2.5.6

---

src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs

Addresses #61.
Two parts to this fix:
1.  Fix bug where shutting down the eventprocessor during startup leads to a state where the partition is not properly terminated and forever tries to acquire the lease.
2. Shut down EventProcessor *immediately* when seeing a ReceiverDisconnectedException; don't wait for EventHubs libary to close the processor. This is intended to fix situations where EventHubs never closes the partitions, or takes too long to close it.

Resilience Improvements for EventHubsProcessor

---

src/DurableTask.Netherite/Abstractions/ITaskHub.cs
src/DurableTask.Netherite/Abstractions/TransportAbstraction.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/Tracing/WorkItemTraceHelper.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/ScriptedEventProcessorHost.cs
src/DurableTask.Netherite/TransportProviders/Memory/MemoryTransport.cs
test/DurableTask.Netherite.Tests/TestConstants.cs
test/DurableTask.Netherite.Tests/TestOrchestrationHost.cs
test/PerformanceTests/host.json
test/PerformanceTests/series/host.neth-12-ls.json

Revised the following heuristics for taking state checkpoints in faster:
1. Do not take time-based checkpoints unless a partition is idle.
2. Do not take state checkpoints when closing individual partitions, only when shutting down the entire hub.
With regard to 1. the setting `MaxTimeMsBetweenCheckpoints` was renamed to `IdleCheckpointFrequencyMs`. The default setting is still 1 minute.

Revise Checkpoint Heuristics

---

docs/hello-sample.md

This pull request contains the extension of the hello-sample GitHub page section with the information necessary to build, run and deploy the new samples introduced in pull request <https://github.com/microsoft/durabletask-netherite/pull/72>

Extended hello-sample

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs

Fixes #69, by setting `CacheOrchestrationCursors` to false when running an out-of-process language.

Set CacheOrchestrationCursors to false for out-of-process languages

---

src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs

FASTER was using the wrong setting which means it runs very slowly after recovery due to an excessive amount of cache misses.

fix recovery parameter for FASTER

---

src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs

To better diagnose failures such as the one reported in #74, create logging entries when taskhub operations are called, completed, or fail with an error.

Add tracing to observe taskhub operations

---

src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/TransportProviders/Memory/MemoryTransport.cs
test/DurableTask.Netherite.Tests/FasterPartitionTests.cs
test/DurableTask.Netherite.Tests/PartitionTestFixture.cs
test/DurableTask.Netherite.Tests/QueryTests.cs
test/DurableTask.Netherite.Tests/ScenarioTests.cs
test/DurableTask.Netherite.Tests/SingleHostFixture.cs

After updating to the latest FASTER, I broke recovery since the delta log was missing. This fixes the missing code in the commit manager.
Also, it adds a new unit test that tests recovery specifically.

Fix NullReferenceException during recovery, add unit test for recovery

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/DurableTask.Netherite/LoadMonitor/LoadMonitor.cs
src/DurableTask.Netherite/Scaling/PartitionLoadInfo.cs

Update the Netherite dlls so we don't force everyone to use netstandard2.1:
```xml
<TargetFrameworks>netstandard2.1;netstandard2.0</TargetFrameworks>
```
This required some small changes to the code (had to remove features that were new in netstandard2.1). Other than that it seems to work.

Support netstandard2.0

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/OrchestrationService/TestHooks.cs
src/DurableTask.Netherite/PartitionState/SessionsState.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
src/DurableTask.Netherite/StorageProviders/Faster/FaultInjector.cs
src/DurableTask.Netherite/StorageProviders/Faster/ReplayChecker.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportProviders/Memory/MemoryTransport.cs
test/DurableTask.Netherite.Tests/TestOrchestrationClient.cs
test/PerformanceTests/Common/Ping.cs
test/PerformanceTests/host.json

Error injection revealed that FASTER hangs in some cases when storage experiences faults.
This causes problem with the automatic recycle in the EventProcessor. 
To avoid this issue, this PR wraps a termination wrapper around all storage calls, which terminates the call if the errorHandler moves to terminated state.
This PR also contains numerous small tracing changes and adds support for running error injection and replay testing inside DF deployments.

Fix hanging storage

---

src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/PartitionState/ReassemblyState.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsSender.cs

fixes problem observed in #105.
The issue was that under failures the EventHubsSender may start over a sequence of fragments before sending the final fragment, and in that case, the receiver has to throw away the partial sequence received earlier, and start over also.

Fix deduplication of fragmented partition and client events

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/Scaling/ScalingMonitor.cs

This PR contains:
1. A fix in the autoscale logic which did lead to high latency not being recognized. This was a regression introduced while implementing the advanced activity scheduling #52.
2. Improved tracing and error handling for the autoscaler logic. In particular, Netherite logs more information to ETW which makes it easier to use Kusto when debugging auto-scaling related issues.
It may be necessary to propagate these changes to the consumption plan support work currently underway by @bachuv.

Fix autoscaler

---

src/DurableTask.Netherite/Abstractions/PartitionState/TrackedObjectKey.cs
src/DurableTask.Netherite/Events/PartitionEvents/Internal/PurgeBatchIssued.cs
src/DurableTask.Netherite/PartitionState/InstanceState.cs
src/DurableTask.Netherite/PartitionState/StatsState.cs
src/DurableTask.Netherite/Scaling/AzureTableLoadMonitor.cs
src/DurableTask.Netherite/Scaling/PartitionLoadInfo.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/CheckpointInfo.cs
src/DurableTask.Netherite/StorageProviders/Faster/ReplayChecker.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/Tracing/PartitionTraceHelper.cs

Add a stats object that tracks the number of instances present in a partition.
This will be used for determining compaction need.
This is also published in the load table.

Maintain a count of instances in each partition

---

src/DurableTask.Netherite/PartitionState/OutboxState.cs

This caused messages to sometimes not be confirmed as persisted, and thus hang around in the outbox even after they were successfully sent.

Fix concurrency bug in outbox

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite/Abstractions/ITaskHub.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportProviders/Memory/MemoryTransport.cs

Several improvements:
- Support DF use of connection name as a comma-separated pair
- Implement staged startup for taskhub (clients first, then workers)
- Expose startup exceptions to client calls
- Create intelligible exception when clients try to connect to a non-existing taskhub
The purpose is to address issues #81, #8, #38.

Support DF clients/connections paradigm

---

src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsConnections.cs

After observing failures where EH creation quickly runs through all retries under conflicts: add delay on conflict, and increase total number of retries.

make EventHubs creation more robust

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs

fixes a problem with status queries that do not contain composite connection name, by auto-completing this if it matches the default provider.

Fix handling of non-composite connection name

---

src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsSender.cs

Fixes several logging statements where the number of arguments was incorrect.

Fix broken logging statements

---

src/DurableTask.Netherite.AzureFunctions/BlobLogger.cs
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite.AzureFunctions/LoggerFactoryWrapper.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProviderPseudoFactory.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProviderStartup.cs
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs

This PR adds more target frameworks to the build, including a special dummy netcoreapp2.2. target that generates a runtime error message when used.
This is intended as a workaround to the legacy bundles build which requires a netcoreapp2 target.

add more target frameworks

---

src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
src/DurableTask.Netherite/Events/PartitionEvents/External/FromLoadMonitor/AcksReceived.cs
src/DurableTask.Netherite/Events/PartitionEvents/External/FromLoadMonitor/SolicitationReceived.cs
src/DurableTask.Netherite/Events/PartitionEvents/Internal/OffloadDecision.cs
src/DurableTask.Netherite/Events/PartitionEvents/Internal/RecoveryCompleted.cs
src/DurableTask.Netherite/Events/PartitionEvents/PartitionEvent.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/OrchestrationMessageBatch.cs
src/DurableTask.Netherite/OrchestrationService/OrchestrationWorkItem.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/Tracing/EventTraceHelper.cs
src/DurableTask.Netherite/Tracing/WorkItemTraceHelper.cs

Three changes in this PR:
- Partitions now appear idle if the messages they process are not considered work, e.g. loadmonitor interactions or recovery events.
- Compaction ETW tracing was broken due to typo. Now fixed.
- Work item tracing is now more uniform.

Fix/Improve tracing of workitems, partition activity, and compaction

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj

This warning is superfluous because we are not actually building a useable library, just a stub that creates an error message at runtime when used.

Suppress warning for netcoreapp2.2

---

src/DurableTask.Netherite/PartitionState/OutboxState.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs

Fixes a bug in a condition that was creating a batch in the outbox with no messages in it, which would then hang around forever because it could not get confirmed.

Fix empty batch in outbox

---

README.md
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj

Quick patch to remove unnecessary dependency
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.5" />
which appears to cause dll issues in the scale controller build.

Create 1.0.3 patch to fix scale controller dll issue

---

src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
src/DurableTask.Netherite/StorageProviders/Faster/LogWorker.cs
src/DurableTask.Netherite/Util/BatchWorker.cs

This PR adds a check to detect whether workers are taking an inordinate amount of time to process a batch.
This is intended to catch observed issues like rare hangs in the synchronous Azure Storage SDK calls.

Add runtime check for batch workers that are stuck

---

src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
test/DurableTask.Netherite.Tests/FasterPartitionTests.cs

Some of the tests failed intermittently because the CacheDebugger monitor had a bug.

Fix cachedebugger test

---

src/DurableTask.Netherite/OrchestrationService/OrchestrationMessageBatch.cs
src/DurableTask.Netherite/PartitionState/SessionsState.cs

When an instance sends a signal to itself, enforce persistence before processing it. This gives entities an easy way to ensure progress is persisted before taking a dependency on it.

Enforce persistence barrier for self-messages

---

src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/AzureStorageDevice.cs

Fix a bug in the code that determines the segment range.
I noticed in the log that the start segment was wrong; it does not appear to cause actual problems.

fix minor bug in AzureStorageDevice

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs

Just as for the Azure Storage provider, we need to set the default for MaxEntityOperationBatchSize in NetheriteProviderFactory, based on the plan.

Set the default for MaxEntityOperationBatchSize

---

src/DurableTask.Netherite/Abstractions/PartitionState/TrackedObject.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterAlt.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/Util/Serializer.cs

Removes the serialization cache because the benefit is unclear with the current design, and it wastes memory.

Remove serialization cache

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/OrchestrationService/TestHooks.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageProviders/Faster/MemoryTracker.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs

Measure cache size after checkpoints to be more robust (prevents incorrect tracking to build up over time).
addresses #132

Measure cache size periodically

---

src/DurableTask.Netherite/StorageProviders/Faster/FasterAlt.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageProviders/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageProviders/Faster/MemoryTracker.cs
src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
src/DurableTask.Netherite/StorageProviders/Faster/TrackedObjectStore.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs

- fix io completion notification handling to avoid creation of an excessive number of continuations
- add memory statistics to compaction trace
- force garbage collection after compaction and after checkpoints

Fix io notification

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProviderPseudoFactory.cs
src/DurableTask.Netherite/Events/EventId.cs
src/DurableTask.Netherite/Events/LoadMonitorEvents/PositionsReceived.cs
src/DurableTask.Netherite/Events/Packet.cs
src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/Tracing/EventTraceHelper.cs
test/DurableTask.Netherite.AzureFunctions.Tests/IntegrationTestBase.cs
test/PerformanceTests/Benchmarks/Counter/Counter.cs
test/PerformanceTests/Benchmarks/Lambdas/ImageRecognitionCaseStudy.cs

This type was causing a compiler warning because it is declared obsolete. Since it appears to be unused, this PR simply removes its uses.

Remove obsolete uses of ConnectionStringResolver

---

src/DurableTask.Netherite/PartitionState/ActivitiesState.cs
src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs

When a partition gets hit with heavy load, it can take a long time until the LoadMonitor starts offloading, if it has not already received information from all other partition.
To avoid this delay, it makes sense to have each partition send this information even if not already requested. By design, there is no per-transaction cost for EventHubs messages, so it is perfectly fine to send periodic messages even if idle.

Send unsolicited partition load information to LoadMonitor

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs

validate that task hubs following the naming convention (should contain only alphanumeric characters, start with a letter, and have length between 1 and 45).

add taskhub name validation

---

src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/ClientRequestEventWithQuery.cs
src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/InstanceQueryReceived.cs
src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/PurgeRequestReceived.cs
src/DurableTask.Netherite/Events/PartitionEvents/PartitionQueryEvent.cs
src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/PartitionState/QueriesState.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Memory/MemoryStorage.cs
test/PerformanceTests/Common/Queries.cs

Fixed several issues:
- for selective queries, paged progress did not work since the query could not advance the continuation token without returning instances.
- queries with time budget did not correctly finish within the budget because it was not being checked in the right place.
- unpaged queries did not use the continuation token correctly which meant that setting pageSize=0 (to force unpaged querying on interfaces that support paged querying) did not work correctly.

Fix query timeouts

---

test/PerformanceTests/Benchmarks/FileHash/FileOrchestration.cs
test/PerformanceTests/Benchmarks/FileHash/GetFilesActivity.cs
test/PerformanceTests/Benchmarks/FileHash/HashActivity.cs
test/PerformanceTests/Benchmarks/Periodic/HttpTriggers.cs
test/PerformanceTests/Benchmarks/Periodic/PeriodicOrchestration.cs
test/PerformanceTests/Benchmarks/WordCount/HttpTriggers.cs
test/PerformanceTests/Benchmarks/WordCount/Mapper.cs

Because anonymous public blob access is discouraged, benchmarks need to once more use a connection string when connecting to the Gutenberg corpus.
Also, updated the periodic test to make it suitable for testing timer-induced scale-from-zero on consumption plans.

update benchmarks for corpus connection, periodic test

---

src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs

In test cases, cache target size is sometimes set to zero. This caused incorrect formatting in some places.

fix corner case for cache size reporting

---

test/PerformanceTests/scripts/deploy.ps1
test/PerformanceTests/scripts/run-scalemonitor.ps1
test/PerformanceTests/series/consumption.ps1

- Update the `deploy.ps1` script so it supports deploying to a consumption plan
- Add a `consumption.ps1` series that runs 7 benchmarks on a consumption plan

update deployment scripts for consumption plan

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite/Connections/ConnectionResolver.cs
src/DurableTask.Netherite/LoadMonitor/LoadMonitorTraceHelper.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/Scaling/AzureBlobLoadPublisher.cs
test/PerformanceTests/host.json

- throw an exception if Azure table name for load publishing is null or empty on a consumption plan (because using blobs for load publishing is not currently supported on the consumption plan).
- fix several places where the test was checking for null, instead of for null or empty.
- update blob load publisher to use the correct partition directories to publish the load.

Validate partition table name on consumption plan

---

src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs

When changing to sdk v12 retries were inadvertently disabled for blob deletions during task hub deletions. This PR re-enables them.

retry blob deletion when taskhubs are deleted.

---

src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs

Two fixes:
1. Make sure assembly name and package name match (for consistency)
2. Add `enableImplicitRegistration = true` to the extension attribute.
- This is because our package has 0 binding attributes in it, the build task skips it unless this is set to `true`.

Fix Az Func dotnet-isolated extension

---

src/DurableTask.Netherite/Util/BatchTimer.cs

As reported in #225, there is currently a bug in BatchTimer: if setting a timer too far in the future, the millisecond-delay exceeds int.MaxValue causing a crash.
The solution is to cap the delay at a safe value, here an arbitrarily chosen 1 day.  This does not interfere with the precision of the timer firing because the ExpirationCheckLoop after the delay passes, the code always rechecks to see if the timer is actually ready to fire based on the current time. It does mean the expiration check loop runs at least once a day, which is o.k.

Fix bug in BatchTimer

---

.github/fabricbot.json

As in title. This will allow FabricBot to manage special labels like "needs: triage" and "needs: author response".

Add FabricBot config for automatic GitHub triaging

---

src/DurableTask.Netherite/Abstractions/TransportAbstraction.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterLog.cs
src/DurableTask.Netherite/StorageLayer/Faster/LogWorker.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs

The following FASTER tuning parameters are immutable, i.e. must not be changed after a task hub is created (or else the storage provider cannot start any more):
- hybrid log page size
- hybrid log segment size
- event log page size
- event log segment size
However, sometimes we *do* need to change these parameters. Most recently (#229), we found that object logs are not collected aggressively enough after compaction, because they hybrid log segment size is much too large. Therefore, we want to change this default.
In this PR, we
- record the above sizes in the `taskhubparameters.json` file of the task hub, so that we can restore them when loading a task hub, which guarantees that parameters *always* match what is in storage even if the defaults change or the user explicitly changes them. …

Overhaul FASTER page and segment size parameters

---

src/DurableTask.Netherite/Events/Fragments/ClientEventFragment.cs
src/DurableTask.Netherite/Events/Fragments/PartitionEventFragment.cs
src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/PartitionState/ReassemblyState.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsSender.cs
src/DurableTask.Netherite/Util/FragmentationAndReassembly.cs

As discovered in #231, there is a bug in the fragmentation/reassembly logic that is exposed in situations where a partition is moved to a different node while it is sending a fragmented event. In that case, fragments of the old sequence can interleave with fragments of the new sequence, which breaks the reassembly logic. 
To fix this, this PR changes the logic so it uses a unique identifier Guid, instead of the event id, to track groups of fragments that belong together. This guarantees that even in interleaving situations, we correctly track each sequence separately.
For compatibility, this change adds the Guid as a nullable new field to the fragment. Old fragments can thus still be deserialized as before, and are treated the same way as before (which is important for not breaking …

Fix fragmentation/reassembly logic

---

src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/Util/BatchTimer.cs

There are currently various issues with how the client behaves when the orchestration service shuts down, including a null reference being thrown as reported in #223.
This PR fixes these issues, making the following changes:
- The orchestration service no longer sets the client to null when stopping. This avoids the null-reference exception.
- The client is stopped after stopping the workers. This helps to keep the client operational for a longer time.
- BatchTimer now shuts down cleanly: has a StopAsync() that waits for the expiration-check loop to exit before returning.
- The client now shuts down cleanly: the StopAsync() goes through all pending client requests and throws a descriptive OperationCanceledException.
- The client now checks for shutdown right after issuing a request. This …

fix various issues with client shutdown

---

test/PerformanceTests/Benchmarks/Semaphore/HttpTriggers.cs
test/PerformanceTests/Benchmarks/Semaphore/Semaphore.cs

This example demonstrates how one can use an entity to implement a semaphore that acts as a global concurrency-limiter for activities.
This was motivated by the discussion in https://github.com/Azure/azure-functions-durable-extension/issues/2434.
To run the tests locally,
1. Modify host.json in the PerfomanceTests project if you want to use AzureStorage provider instead of Netherite
2.  Set environment variables for `AzureWebJobsStorage` and `EventHubsConnection` (don't need the latter unless using Netherite)
3. Start PerformanceTests function app 
4. Launch 1000 orchestrations by `curl http://localhost:7071/start -d OrchestrationWithSemaphore.1000`
5. Observe progress of the orchestrations by calling `curl http://localhost:7071/query`
6. Observe state of the semaphore by calling  `curl …

Add semaphore example to PerformanceBenchmarks

---

src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs

This was an oversight when committing #235.
It means that the memory is not being correctly set, but always uses the default. This may have also inadvertently caused recovery failures when opening task hubs created with an older version.

Fix ignored tuning parameter

---

src/DurableTask.Netherite/PartitionState/OutboxState.cs

Fixes a problem discovered during testing.
While iterating over the collection of messages to send, even if this is just a single message, the send can actually complete, and the send confirmation can also complete, at which point the element may be removed from the collection, which causes a conflict with the initial loop iteration as we see here:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at DurableTask.Netherite.OutboxState.Send(Batch batch) in D:\git\durabletask-netherite\src\DurableTask.Netherite\PartitionState\OutboxState.cs:line 112
at DurableTask.Netherite.DurabilityListeners.ConfirmDurable(Event evt) in D:\git\durabletask-netherite\src\DurableTask.Netherite\Util\DurabilityListeners.cs:line 79
at …
```

Fix race condition in OutboxState

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs

Sometimes the scale monitor is called with null metrics. These are transient occurrences. Instead of throwing an exception, we handle this gracefully.
Fixes #246.

Fix null metrics exceptions

---

src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
src/DurableTask.Netherite/Abstractions/PartitionState/TrackedObject.cs

fix bug where an effect is applied twice due to an RMW executing twice in FASTER, as discovered and discussed in #236. The results are pretty unpredictable, state can get corrupted.
The fix is to record the log commit number of the last-applied event in the tracked object, and then use that to filter duplicate applications of the same event. It is not necessary to store this number with the tracked object, in-memory-only is sufficient (since the double RMW does not actually get committed).
This may also have had other manifestations that went undetected.

Fix double application of partition events on tracked objects

---

src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs

The current implementation has many exception handlers that deliberately exclude fatal exceptions. While testing in the cloud, I noticed that this has some real disadvantages in some cases:
- The out of memory exception is typically not getting logged anywhere, so we have no infomation on what happened. This is not a good idea because sometimes a single stack trace can reveal some bug or configuration error and help us diagnose and fix the problem. If we are not logging anything, we are much less likely to be able to address the underlying issues.
- The out of memory exception is NOT guaranteed to instantly terminate the process. So, we still have to terminate as cleanly as we can, otherwise the application may continue to run partially, now in a bad state, and even do real damage (e.g. …

update fatal exception handling

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/Scaling/LoadPublishWorker.cs

The load publisher contained a bug where the `FlushAsync` basically only worked the first time, because it was using a single cancellationTokenSource. After that, the load publisher would run much too frequently. Also, this source was not properly disposed.
We fix this by using a TaskCompletionSource instead, and creating a new one for every invocation of FlushAsync.

fix LoadPublisher.FlushAsync

---

src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs

I observed cases where partitions fail to start repeatedly. To reduce CPU waste and log pollution in those situations, this PR adds a backoff delay between retries.

limit frequency of failing partition starts

---

src/DurableTask.Netherite/Scaling/AzureTableLoadPublisher.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/AzureStorageDevice.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterAlt.cs

Fixes a few omissions in code that uses the Azure Storage SDK:
1. do not report an error when retrying a delete and the blob was already deleted.
2. make sure to call Dispose() on all Azure responses that are IDisposable. This is a new requirement for Azure v12 SDK; previously, there was no such obligation on behalf of the caller.
Also, this PR removes a dependency on `FirstAsync` (a LINQ utility function for AsyncEnumberables) because this caused dependency issues for some .NET targets.

Fixes to azure storage calls

---

src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs

Undoes a FASTER tuning parameter change that caused unexpected excessive baseline memory usage even without any significant load.
This change was introduced in release 1.3.3 and seems to have caused a lot of OOM issues (e.g. #263) and otherwise degraded performance due to the higher memory pressure.

Fix excessive memory use introduced in release 1.3.3

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs

As in title, necessary for ScaleControllerV3 to operate without error'ing.
We need uniquely named scaleMonitors in Sc V3,  and the functionId gives us that distinction

Use functionId in scaleMonitorDescriptor

---

src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsClientSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsConnections.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/LoadMonitorSender.cs
src/DurableTask.Netherite/Util/BatchWorker.cs

To avoid exceptions during host shutdowns, this PR adds code that cleanly terminates the event hubs senders before stopping the event hub clients.
It works as follows:
- a cancellation token is passed to the batchworker that performs the sending.
- this token is triggered as the first thing when a host is shutting down.
- from that point on, the batchworker will no longer process new events.
- at some point during shutdown, we call `WaitForShutdownAsync()`.
- only after that do we destruct the event hub client that constructed the sender.
This guarantees that the sender is no longer active by the time we close the client.

Implement clean shutdown of Event Hubs senders

---

src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
src/DurableTask.Netherite/Abstractions/PartitionState/IPartitionState.cs
src/DurableTask.Netherite/Abstractions/TransportAbstraction.cs
src/DurableTask.Netherite/Events/Packet.cs
src/DurableTask.Netherite/Events/PartitionEvents/PartitionEvent.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/PartitionState/DedupState.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/CheckpointInfo.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterAlt.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/StorageLayer/Faster/ReplayChecker.cs
src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs
src/DurableTask.Netherite/StorageLayer/Faster/TrackedObjectStore.cs
src/DurableTask.Netherite/StorageLayer/Faster/TrackedObjectStoreEffectTracker.cs
src/DurableTask.Netherite/StorageLayer/Memory/MemoryStorage.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsClientSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsConnections.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/LoadMonitorProcessor.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/ScriptedEventProcessorHost.cs
src/DurableTask.Netherite/TransportLayer/SingleHost/PartitionQueue.cs
src/DurableTask.Netherite/Util/FragmentationAndReassembly.cs

This PR implements a new mechanism for optimizing the EH sender throughput.
Previously we observed in multiple cases that the limited throughput when sending data to a single partition caused bottlenecks in the application (#268, #240). 
With this new mechanism, anytime a partition sender needs to send large amounts of data (large messages, or many small messages), it does not send the messages directly via EH, but writes them to a blob batch, then sends a message containing the blob name. The receiver then loads the data from the blob batch. 
This may also resolve #272 since it replaces some of the code that was identified as the likely source of the error.

implement blob batching to improve EH sender throughput

---

src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs

Addresses observed issue where compaction sizes grew too large, causing out of memory.
The fix is to adjust the heuristics so that they never compact more than a fixed limit.
Also, the heuristics no longer suppress compaction based on the size of the mutable section since that can have unpredictable effects on log size management. Instead, compaction is now gated by a minimum on the area being compacted.

limit compaction size by absolute size, not relative size

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/PerformanceTests/PerformanceTests.csproj

Updates to
Microsoft.Azure.DurableTask.Core  2.13.0
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.9.6
and a few other minor versions (Azure storage, EventHubs).
Also, removes the unnecessary net5.0 target which was causing build warnings.

update versions and remove net5.0 target

---

src/DurableTask.Netherite/Abstractions/TransportAbstraction.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterAlt.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsSender.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportLayer/ITransportLayer.cs
src/DurableTask.Netherite/TransportLayer/SingleHost/SingleHostTransportProvider.cs

Currently, most of the code ignores fatal exceptions (such as OOM). The problem with that is that if a host crashes due to OOM it does not release the storage leases, which means no other host can pick up the partition until the lease expires (30s). 
To address this, this PR adds a new mechanism to deal with fatal exceptions on partitions. When experiencing a fatal exception within a partition, the partition error handler takes notice and *immediately* shuts the transport layer. This shutdown quickly tries to release all leases. This allows partitions to more quickly restart on other nodes.

Revise handling of fatal exceptions

---

src/DurableTask.Netherite/StorageLayer/Faster/LogWorker.cs

Several changes, to deal with recently observed fatal deserialization errors that can make partitions permanently unusable.
1. Adds detailed tracing (enabled only at lowest Trace level) that collects detailed information about each portion of data written to and read from the log.
2. Collects more information about the thrown deserialization exceptions.
3. Catches the deserialization exceptions and tries to continue as best as possible, ignoring the particular event that threw the exception.

Instrument event-log serialization/deserialization

---

src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/ScriptedEventProcessorHost.cs

Fixes a bug where discarding events from other taskhubs causes the expected sequence number to be wrong (not updated to reflect the discarded packets) which then triggers spurious errors when receiving more events.
This code is not tested yet.

fix discard of packets so the next packet to expect is updated correctly

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs

This PR appends a GUID to the scale monitor descriptor to make it unique because customers have been seeing this exception - `System.ArgumentException : An item with the same key has already been added.`
This PR is used to create a private package for a customer to get this fix but it will get merged once the fix is validated.

Create unique scale monitor descriptors

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs

Mistakenly merged https://github.com/microsoft/durabletask-netherite/pull/290 into the wrong branch (main instead of dev).
Also, the PR was setting the version to a private prerelease which is not correct.
This reverts commit 3a2d193e57d528d1664005781e2cce993b2794a2.

Revert "initial commit (#290)"

---

src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs

implements a watchdog that terminates CompletePending quickly if it hangs.
This is meant as a temporary mitigation until we find and fix the root cause of #251.

Mitigation for StoreWorker hangs

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs

This is an updated version of the previous PR https://github.com/microsoft/durabletask-netherite/pull/290 (which I had merged by mistake and then reverted).

fix scalemonitor descriptor

---

src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs

reported CacheMB size has apparently been broken due to a trivial math error since this PR: [fix corner case for cache size reporting by sebastianburckhardt · Pull Request #203 · microsoft/durabletask-netherite (github.com)](https://github.com/microsoft/durabletask-netherite/pull/203/files)
Easily fixed by this PR.

fix cache size reporting

---

src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs

This PR fixes a problem with how Netherite uses the asynchronous checkpointing support in FASTER.
The problem was that there were races between the checkpoint thread and the main session.
@badrishc  suggested to fix this by waiting, after initiating the checkpoint, for the main session to advance to the next version.
I added that loop, together with some safety limit on how long to wait.
Fixes https://github.com/microsoft/durabletask-netherite/issues/325

Fix fencing of checkpoints

---

src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs

Several compiler warnings were introduced by recent changes. 
This PR reverts the changes.

Fix compiler warnings about use of nullable features in non-nullable code

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/Util/PartitionTimeout.cs

While analyzing https://github.com/Azure/azure-functions-durable-extension/issues/2603 we noticed that in some cases, partition startup takes an extraordinary amount of time. This may be caused by hangs or other reasons.
To better diagnose this type of issue, and to make it can recover from indefinite hangs, this PR makes the following changes:
1. It adds a "waiting" transition prior to the "starting" transition. This allows us to differentiate between time spent waiting for the MaxConcurrentStarts semaphore, and the actual time spent starting up the partition.
2. I adds a timeout to the partition startup. This timeout is configurable in the settings. The default is 15 minutes for now.

Revise partition startup

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/Util/BlobUtils.cs

While analyzing some of traces showing high client latencies (see https://github.com/Azure/azure-functions-durable-extension/issues/2603) we discovered a problem: in some cases the partition lease is not released when the partition is terminated, because the request is cancelled. This causes an excessive delay before the partitition recovery, since the lease has to expire first. Waiting for the lease to expire can take up to 40s and delays all pending client requests to that partition.
This PR fixes this problem by not passing the termination cancellation token to the lease renewal (which caused the lease release to not happen).

Always release partition lease when a partition shuts down

---

src/DurableTask.Netherite/Abstractions/PartitionState/TrackedObjectKey.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs

To help us better diagnose and debug data corruption issues:
1) when deserializing data from storage, do more validation to better detect and report typical manifestations of data corruption (e.g. enumerations outside of range, streams not containing enough bytes).
2) if observing errors in deserialization or serialization, terminate the partition with a corresponding error message that is easily visible in the logs.
3) Skip deserialization when a partition is already terminated (this also provides a quick workaround for https://github.com/microsoft/FASTER/issues/883).

Enhance validation of deserialization and reporting of errors

---

src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs

Testing revealed issues where partitions continuously fail because of supposed "out-of-order" packets. What is actually happening is that the redelivery of previously delivered packets is sometimes not working correctly after a partition terminates.
I tracked this down to the fact that the event hubs transport may be inadvertently cancelling storage requests that retrieve the batch contents when the partition is terminated, which is incorrect (loading the batch content is not tied to the partition state and should be succeeding even if the partition is recycled). This means some packets are skipped and never delivered. 
This PR fixes the problem by using the correct cancellation token.
It also adds a condition to the message to check whether any cancellations are o.k. (so that inadvertent …

fix EH batch load cancellation issue

---

src/DurableTask.Netherite/Abstractions/PartitionState/IPartitionErrorHandler.cs
src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterLog.cs
src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/SingleHost/PartitionQueue.cs

There are a number of tasks that need to execute after a partition has shut down.
These dispose tasks were previously registered as events. 
For more uniform handling of timeouts and error reporting, this PR now allows disposal tasks to be registered with timeouts, and generates consistent partition error messages when any of the tasks throw or do not complete in time.

Revise how dispose tasks are organized 

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/Abstractions/PartitionState/IPartitionErrorHandler.cs
src/DurableTask.Netherite/Abstractions/PartitionState/TrackedObjectKey.cs
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/OrchestrationService/Partition.cs
src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/AzureStorageDevice.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/StorageOperations.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterLog.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/SingleHost/PartitionQueue.cs
src/DurableTask.Netherite/Util/BlobUtils.cs
src/DurableTask.Netherite/Util/PartitionTimeout.cs
src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs

Promote dev to main for 1.4.2 release

---

src/DurableTask.Netherite/OrchestrationService/Client.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs

Currently, long or infinite timeout arguments to `IOrchestrationServiceClient.WaitForOrchestrationAsync` are not correctly handled:
1. infinite timeouts (-1 milliseconds) are ignored and instead time out immediately
2. long timeouts can lead to state pollution because they are persisted in the partition state until the timeout expires, even if the client is long gone.
To fix this, this PR adds some code to break long or infinite timeouts into 5-minute portions. It runs these portions in a loop until the timeout expires or the wait completes with a result.

support long and infinite timeouts in WaitForOrchestrationAsync

---

src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/AzureStorageDevice.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobEntry.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/StorageOperations.cs

We observed an unnaturally large number of errors like "storage operation id=2438 has exceeded the time limit 00:01:30" that terminate the partition.
After analysis we found that this is caused by situations where a blob creation simultaneously succeeds (i.e. blob was created) and times out. Our retry path was not correctly detecting that the blob was already created.
This PR:
- fixes a missing check in the retry condition to avoid unlimited retries
- adds the id into the traces for the blob creation for easier diagnostics
- if the blob already exists, loads the e-tag, and skips the next attempt

Fix hanging blob creation

---

test/PerformanceTests/Benchmarks/Store/HttpTriggers.cs
test/PerformanceTests/Benchmarks/Store/Store.cs

New http triggers for storing random data of a specified size in entities. 
Contains the following triggers:
-  POST store/{key}
sets the entity with key {key} to contain as many random bytes as specified in the request body
-  GET store/{key}
return the number of bytes stored in the entity with key {key}
-  DELETE store/{key}
deletes the entity with key {key}
-  POST storevector/{prefix}/{count} 
sets the entities with keys {prefix0} ... {prefix{count-1}} to contain as many random bytes as specified in the request body
-  DELETE storevector/{prefix}/{count}
deletes the entities {prefix0} ... {prefix{count-1}}
I use this in conjunction with scripts in my stress tests.

Add variable-sized generic entity benchmark

---

src/DurableTask.Netherite/OrchestrationService/Client.cs

Similar change as https://github.com/Azure/durabletask/pull/1060.
This is a coordinated change relating to this Durable Functions PR: https://github.com/Azure/azure-functions-durable-extension/pull/2779
Should be non-breaking because `OrchestrationAlreadyExistsException` already derives from `InvalidOperationException`.

Use OrchestrationAlreadyExistsException instead of InvalidOperationException

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs

In the current code, the `BatchProcessed` event was copying the list `NewEvents` from `OrchestrationRuntimeState`. However, that list can be mutated when processing more batches. This violates the design principle that events should be immutable, and can lead to race conditions between code that is reading those events (e.g. for serialization) and code that is mutating it.
To fix this, we just make a copy of that list when constructing the `BatchProcessed` event.

fix race condition on OrchestrationRuntimeState.NewEvents

---

src/DurableTask.Netherite/PartitionState/PrefetchState.cs

During stress testing we observed to our surprise that event hubs sometimes duplicates events internally. Specifically, it is possible for an event to be successfully sent by a partition client only once, but then this event appears twice in the delivery sequence to the partition, with two different sequence numbers. Specifically we saw the same event being delivered at positions 2115 and 2121. The events in between (positions 2116 to 2120) corresponded to events that were sent from a different source.
Thankfully the practical impact of this discovery is relatively minor since we are already deduplicating almost all events. The only events not being duplicated are client requests that are sent from a client to a partition.
Netherite was designed assuming this would not happen, so we …

Ignore duplicate client requests

---

src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs
src/DurableTask.Netherite/Tracing/EtwSource.cs
src/DurableTask.Netherite/Tracing/EventTraceHelper.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsTransport.cs
src/DurableTask.Netherite/TransportLayer/EventHubs/LoadMonitorProcessor.cs

Fixes #363.
Previously, the code determined whether it was safe to delete a blob batch by checking the last update event for persistence. However, since there could still be read events after the update event, it meant that the blob may be deleted too early (and then hit a missing blob exception when trying to fetch the blob). This was observed in #363.
A similar mechanism was also used to determine whether a batch needed to be kept around for redelivery when reincarnating a partition. This has the same problems: a batch could be removed from the redelivery queue too early.
This PR fixes and simplifies this problem by
a) precisely tracking the persistence state of a batch by using the full position tuple (seqno, batchpos) in the redelivery queue, as opposed to only using the seqno. Read …

Fix blob batch persistence

---

src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/AzureStorageDevice.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/Util/BlobUtils.cs

Based on observations in recent stress testing runs, this PR makes the following adjustments:
1. add tracing when making cancellation callbacks to FASTER, since we are suspecting hangs
2. adjust timeout parameter
3. recognize a couple more transient socket exceptions

Make adjustments and add tracing

---

README.md
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs

Since 1.5.0 is currently delayed by issues in the FASTER release pipeline, we are releasing a 1.4.3 patch release containing the many other fixes since 1.4.2

go back to version 1.4.3 to do a quick patch release

---

src/DurableTask.Netherite/PartitionState/InstanceState.cs

Discovered more fallout from EH internal event duplication (as first observed in #379).
Specifically, it is possible for a creation request to be processed twice, thereby starting a duplicate work item, and this duplicate work item later creates corruption in the history (multiple execution started events) since both work items have the same execution id.
To fix this I stores the request id of the creation request that created the orchestration instance, and use that to filter duplicate deliveries of the same event.

Deduplicate CreationRequestReceived events

---

test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/PerformanceTests/PerformanceTests.csproj

These direct package references are unncessary as those can be resolved via existing project references.

Cleanup unnecessary references.

---

src/DurableTask.Netherite/DurableTask.Netherite.csproj

As in title - FASTER release made a hotfix for us here: https://github.com/microsoft/FASTER/pull/916

Increase FASTER.Core to 2.6.5

---

src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
src/DurableTask.Netherite.AzureFunctions/NetheriteProviderStartup.cs
src/common.props

There are two `NetheriteProviderFactory` constructors: https://github.com/microsoft/durabletask-netherite/blob/f3e5f2621f05d615d52fd6005bf9c6d6d811ce99/src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs#L51-L109 . One is obsolete, and the other is not.
We used the `ActivatorUtilitiesConstructor` to tell DI which constructor to choose. However, it seems that annotation isn't honored in .NET8: https://github.com/dotnet/runtime/issues/95915.
Due to some combination of this .NET8 change, and the Host for Flex Consumption using a new DI library, DF apps in Flex Consumption using bundles are now failing with the following exception:
> System.InvalidOperationException : Unable to activate type 'DurableTask.Netherite.AzureFunctions.NetheriteProviderFactory'. The following …

Disambiguate NetheriteFactory constructor and rev version

---

eng/ci/official-build.yml
eng/templates/build.yml

This PR migrates the pipelines to 1ES pipelines. It adds 2 files - official-build.yml and build.yml. official-build.yml references build.yml and runs on any changes pushed to the `main` branch.

Migrate to 1ES pipelines

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj

Fixes broken build in some environments where TFM build warnings were treated as errors.
The fix is simply suppressing those warnings, specifically for the 2.2 target which is a dummy target. I also updated the comments.

fix build break by suppressing tfm build warnings

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/StorageLayer/Faster/FaultInjector.cs
src/common.props
test/DurableTask.Netherite.Tests/FaultInjectionTests.cs
test/DurableTask.Netherite.Tests/HostFixture.cs

Fix: https://github.com/microsoft/durabletask-netherite/issues/352
We know that `StartAsync` can be called by the Functions Host several times during start up, and therefore it should be possible to call this method more than once an obtain a different result. Today, that's not possible since we cache the exception.
This PR is a naive first attempt at addressing this: it discard the cached exception whenever "StartAsync" is invoked. This means that "early" attempts at creating clients will fail (as they'll reference the cached exception, but the Host should be clear to make progress on subsequent calls to `StartAsync`.
Open questions:
(1) Is there more cached state to clear? For example - `this.checkedClient` or `this.client`?
(2) What is the lifecycle of StartAsync? Is it guaranteed that …

Clear cached exception when StartAsync is invoked

---

Directory.Build.targets
DurableTask.Netherite.sln

The Netherite version of this PR: https://github.com/Azure/durabletask/pull/1147
In short, since the code is now built from a _mirror_ of the GitHub code inside Azure DevOps, we're losing some source link information at built-time. This MSBuild file manually indicate that the code is coming from GitHub, despite building from ADO

Add source link reconstruction

---

eng/ci/official-build.yml
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj

As in title, add README to packages, to remove warning when uploading to NuGet
And add partial CodeQL support by making official builds run weekly

Add readme and official build codeql

---

src/DurableTask.Netherite/StorageLayer/Faster/CacheDebugger.cs
src/DurableTask.Netherite/StorageLayer/Faster/CheckpointInjector.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs
test/DurableTask.Netherite.Tests/ConcurrentTestsFaster.cs

We have seen a lot of hangs recently in the CI, which seem to not be caused by recent changes but look a bit like errors in the test framework. I created this PR as a way to further investigate and hopefully fix these hangs.
In this first step, I am trying to understand hangs in the QueriesCopyToTail test which I have seen repeatedly in CI. The hangs seem to have something to do with the checkpoint injection mechanism used by the test. To narrow this down, we revise this state machine and add lots of tracing.

Debug hangs in CI

---

README.md
samples/Hello_Netherite_with_DotNetCore/HelloDF.csproj
samples/TokenCredentialDF/TokenCredentialDF.csproj
samples/TokenCredentialDTFx/TokenCredentialDTFx.csproj
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
src/common.props
test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/DurableTask.Netherite.Tests/DurableTask.Netherite.Tests.csproj
test/DurableTask.Netherite.Tests/ScenarioTests.cs
test/LoadGeneratorApp/LoadGeneratorApp.csproj
test/PerformanceTests/Benchmarks/EventHubs/ProducerEntity.cs
test/PerformanceTests/Benchmarks/Sequence/BlobSequence.cs
test/PerformanceTests/Benchmarks/Sequence/QueueSequence.cs
test/PerformanceTests/PerformanceTests.csproj

In preparation of the 2.0.0 release:
- increases the version number for all packages
- updates to the latest durable task dependencies
- updates most other packages to the latest versions
- removes the netcoreapp2.2 target which was a 'dummy' target that is no longer needed I think

increase major version (2.0.0) and update packages

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/Scaling/AzureBlobLoadPublisher.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterStorageProvider.cs
test/PerformanceTests/host.json

Adds a new parameter to the `NetheriteOrchestrationServiceSettings`:
```csharp
/// <summary>
/// The path to the file containing the taskhub parameters.
/// </summary>
public string TaskhubParametersFilePath { get; set; } = "taskhubparameters.json";
```
This allows us to keep multiple "versions" of a taskhub in storage by using different task hub parameters files. Specifically, we intend to use this to debug potential corruptions in FASTER, by using this parameter in conjunction with the RecoveryTester feature.

Add a configuration parameter for specifying the task hub parameters file

---

src/DurableTask.Netherite/TransportLayer/EventHubs/EventProcessorHost.cs

As observed in https://github.com/microsoft/durabletask-netherite/issues/430, the handler registration was missing.
This appears to be a simple copy-paste mistake but it was not caught by testing because the tests use the other constructor overload.

Fix missing ProcessPartitionEventAsync handler

---

src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/CheckpointInfo.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
src/DurableTask.Netherite/StorageLayer/Faster/FasterTraceHelper.cs
src/DurableTask.Netherite/StorageLayer/Faster/LogWorker.cs
src/DurableTask.Netherite/StorageLayer/Faster/PartitionStorage.cs
src/DurableTask.Netherite/StorageLayer/Faster/StoreWorker.cs

In light of recent issues with FASTER crashing repeatedly during recovery, while replaying the commit log, this PR implements several steps that should help us troubleshoot the issue (and possibly mitigate it).
1. We are adding a recovery attempt counter to the last-checkpoint.json file so we can detect if partition recovery is repeatedly failing.
2. If the number of recovery attempts is between 3 and 30, we are boosting the tracing for the duration of the recovery. This may help us investigate the location of where the crash happens.
3. If the number of recovery attempts is larger than 6, we are disabling the prefetch during the replay. This means FASTER is executing fetch operations sequentially during replay, which slows down the replay A LOT but makes it more deterministic so we can …

Implement detection and potential mitigation of recovery failure cycles

---

src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/common.props
test/PerformanceTests/Benchmarks/Sequence/HttpTriggers.cs

As titled. This PR updates the below dependencies to start the Netherite v2.2.0 release:
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.13.6 -> 3.0.0
Microsoft.Azure.DurableTask.Core 2.17.1 -> 3.0.0

Update Durable Dependencies Version for v3.0.0 Release

---

src/DurableTask.Netherite.AzureFunctions/NetheriteTargetScaler.cs
test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/DurableTask.Netherite.AzureFunctions.Tests/TargetBasedScalingTests.cs

I added a lot more unit tests for the target-based scaling feature, to exercise the logic in various places.
I also found two bugs in the scaling logic using these tests, and fixed them.

add unit tests for target based scaling, and fix 2 bugs found by tests

---

Directory.Packages.props
samples/HelloDTFx/HelloDTFx/HelloDTFx.csproj
samples/Hello_Netherite_with_DotNetCore/HelloDF.csproj
samples/Hello_Netherite_with_Python/extensions.csproj
samples/Hello_Netherite_with_TypeScript/extensions.csproj
samples/TokenCredentialDF/TokenCredentialDF.csproj
samples/TokenCredentialDTFx/TokenCredentialDTFx.csproj
src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
src/DurableTask.Netherite/DurableTask.Netherite.csproj
src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
test/DurableTask.Netherite.Tests/DurableTask.Netherite.Tests.csproj
test/LoadGeneratorApp/LoadGeneratorApp.csproj
test/PerformanceTests/PerformanceTests.csproj

This PR moves to [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management)
- Add Directory.package.props for CPM.
- Remove all versions at each csproj

Move to Central Package Management

---

test/PerformanceTests/Dockerfile

Updating `mcr.microsoft.com/azure-functions/dotnet:3.0` to `mcr.microsoft.com/azure-functions/dotnet:3.0.15960`.
3.0.15960 is listed in [https://mcr.microsoft.com/v2/azure-functions/dotnet/tags/list](https://mcr.microsoft.com/v2/azure-functions/dotnet/tags/list)

Bump azure-functions/dotnet from 3.0 to 3.0.15960 in /test/PerformanceTests
