microsoft/durabletask-netherite

- test/PerformanceTests/Orchestrations/ProducerConsumer/Completion.cs
- test/PerformanceTests/Orchestrations/ProducerConsumer/Consumer.cs
- test/PerformanceTests/Orchestrations/ProducerConsumer/Parameters.cs
- test/PerformanceTests/Orchestrations/ProducerConsumer/Producer.cs
- test/PerformanceTests/Orchestrations/ProducerConsumer/ProducerConsumer.cs
- test/PerformanceTests/Orchestrations/ProducerConsumer/ProducerConsumerOrchestration.cs
- test/PerformanceTests/host.json
For measuring throughput between entities.
> Add ProducerConsumer performance test

- test/PerformanceTests/Orchestrations/WordCount/HttpSurface.cs
- test/PerformanceTests/Orchestrations/WordCount/Mapper.cs
- test/PerformanceTests/Orchestrations/WordCount/Reducer.cs
- test/PerformanceTests/Orchestrations/WordCount/Summary.cs
- test/PerformanceTests/host.json
New map-reduce style test that counts words, using entities.
> Wordcount performance test

- DurableTask.Netherite.sln
- ScalingTests/ConsoleLoggerProvider.cs
- ScalingTests/Program.cs
- ScalingTests/ScalingTests.csproj
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
- src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/OrchestrationService/Partition.cs
- src/DurableTask.Netherite/PartitionState/ActivitiesState.cs
- src/DurableTask.Netherite/PartitionState/SessionsState.cs
- src/DurableTask.Netherite/Scaling/AzureLoadMonitorTable.cs
- src/DurableTask.Netherite/Scaling/LoadPublisher.cs
- src/DurableTask.Netherite/Scaling/PartitionLoadInfo.cs
- src/DurableTask.Netherite/Scaling/ScaleRecommendation.cs
- src/DurableTask.Netherite/Scaling/ScalingMonitor.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
- src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
- src/DurableTask.Netherite/Tracing/EtwSource.cs
- src/DurableTask.Netherite/Tracing/PartitionTraceHelper.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
- test/EventConsumer/EventConsumer.csproj
- test/EventConsumer/host.json
- test/PerformanceTests/PerformanceTests.csproj
- test/PerformanceTests/host.json
- test/PerformanceTests/scripts/deploy.ps1
Addresses #3.
Requires the changes in azure/azure-functions-durable-extension#1692, so we have to wait for that PR before merging this.
> Support autoscaling on elastic premium plans

- samples/Hello/host.json
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
- test/PerformanceTests/host.json
- test/PerformanceTests/scripts/deploy.ps1
- test/PerformanceTests/scripts/run.ps1
introduce 'CacheOrchestrationCursor' setting, instead of using ExtendedSessionsEnabled.
> Add CacheOrchestrationCursor setting.

- src/DurableTask.Netherite/OrchestrationService/ActivitySchedulerOptions.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
- src/DurableTask.Netherite/PartitionState/ActivitiesState.cs
- test/PerformanceTests/host.json
- test/PerformanceTests/series/host.neth-12-ls.json
fix replay bug in activity scheduler, and add configuration setting.
> Fix Activity Scheduler and Add Configuration Setting

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/Util/ChannelReaderExtensions.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/IntegrationTestBase.cs
- test/PerformanceTests/PerformanceTests.csproj
To avoid dll loading issues as described in #55.
> Fix dll load problem and throw exception on 32 bit

- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/ClientTaskMessagesReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/CreationRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromPartitions/ActivityOffloadReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromPartitions/PartitionMessageEvent.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromPartitions/RemoteActivityResultReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromPartitions/TaskMessagesReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/ActivityCompleted.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/BatchProcessed.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/TimerFired.cs
- src/DurableTask.Netherite/Events/PartitionEvents/PartitionEvent.cs
- src/DurableTask.Netherite/Events/PartitionEvents/PartitionUpdateEvent.cs
- src/DurableTask.Netherite/OrchestrationService/Client.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/OrchestrationService/Partition.cs
- src/DurableTask.Netherite/PartitionState/OutboxState.cs
- src/DurableTask.Netherite/PartitionState/SessionsState.cs
- src/DurableTask.Netherite/PartitionState/TimersState.cs
- src/DurableTask.Netherite/Tracing/EtwSource.cs
- src/DurableTask.Netherite/Tracing/WorkItemTraceHelper.cs
Change the way the TaskMessages are traced to provide more consistent results.
> Improve ETW message tracing

- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/ClientTaskMessagesReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/CreationRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/DeletionRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/HistoryRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/StateRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/WaitRequestReceived.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/BatchProcessed.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/TimerFired.cs
- src/DurableTask.Netherite/Events/PartitionEvents/PartitionEvent.cs
- src/DurableTask.Netherite/LoadMonitor/LoadMonitor.cs
- src/DurableTask.Netherite/OrchestrationService/Client.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/OrchestrationService/Partition.cs
- src/DurableTask.Netherite/PartitionState/HistoryState.cs
- src/DurableTask.Netherite/Scaling/LoadPublisher.cs
- src/DurableTask.Netherite/Scaling/ScalingMonitor.cs
- src/DurableTask.Netherite/Tracing/EtwSource.cs
- src/DurableTask.Netherite/Tracing/EventTraceHelper.cs
- src/DurableTask.Netherite/Tracing/OrchestrationServiceTraceHelper.cs
- src/DurableTask.Netherite/Tracing/WorkItemTraceHelper.cs
Various fixes to tracing to improve the ETW events.
> Improve Tracing

- docs/hello-sample.md
As discussed in issue #85 I have enhanced the description of the sample with an additional section on the video describing the walk through.
> Add section on migration video

- samples/Hello_Netherite_with_Python/extensions.csproj
- samples/Hello_Netherite_with_TypeScript/extensions.csproj
- samples/Hello_Netherite_with_TypeScript/package-lock.json
- samples/Hello_Netherite_with_TypeScript/package.json
Update extensions and use latest TypeScript package.
> Fix samples to use latest dependencies

- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/Scaling/ScalingMonitor.cs
> fix nullref in scale monitor

- test/LoadGeneratorApp/BaseParameters.cs
- test/LoadGeneratorApp/Client.cs
- test/LoadGeneratorApp/Dispatcher.cs
- test/LoadGeneratorApp/FixedRateParameters.cs
- test/LoadGeneratorApp/Results.cs
fix compiler warnings in load generator
> fix warnings

- src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
This bug was introduced in #82 and caused slow startup
> fix bug in client connection establishment

- src/DurableTask.Netherite.AzureFunctions/NetheriteProvider.cs
- src/DurableTask.Netherite/Abstractions/IOrchestrationServiceQueryClient.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/CoreScenarios.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/IntegrationTestBase.cs
- test/DurableTask.Netherite.Tests/QueryTests.cs
- test/DurableTask.Netherite.Tests/TestOrchestrationClient.cs
- test/DurableTask.Netherite.Tests/TestOrchestrationHost.cs
Also fixes test that ignored continuation token.
> Encapsulate orchestration service query API in interface

- src/DurableTask.Netherite/StorageProviders/Faster/TrackedObjectStoreEffectTracker.cs
- test/DurableTask.Netherite.Tests/ScenarioTests.cs
Fixes bug introduced in recent refactoring of EffectTracker.
> fix missing await for task in ApplyToStore

- samples/Hello_Netherite_with_TypeScript/package-lock.json
- samples/Hello_Netherite_with_TypeScript/package.json
now using durable-functions 1.5.4.
> Update TypeScript sample

- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsProcessor.cs
- src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
- test/DurableTask.Netherite.Tests/FasterPartitionTests.cs
- test/DurableTask.Netherite.Tests/QueryTests.cs
- test/DurableTask.Netherite.Tests/TestOrchestrationHost.cs
- test/ScaleMonitor/Program.cs
Add more tracing for eventhubs, and use IOrchestrationService interface to more clearly indicate which calls are part of the interface.
> Minor tracing changes and refactoring

- src/DurableTask.Netherite/Abstractions/IStorageProvider.cs
- src/DurableTask.Netherite/Abstractions/TransportAbstraction.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterStorage.cs
- src/DurableTask.Netherite/TransportProviders/EventHubs/EventHubsTransport.cs
- src/DurableTask.Netherite/TransportProviders/Memory/MemoryTransport.cs
- test/DurableTask.Netherite.Tests/TaskhubTests.cs
use path prefix to solve atomicity of taskhub creation/deletion
> Fix taskhub management

- src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs
- src/DurableTask.Netherite/Events/PartitionEvents/Internal/SendConfirmed.cs
- src/DurableTask.Netherite/OrchestrationService/TestHooks.cs
- src/DurableTask.Netherite/PartitionState/ActivitiesState.cs
- src/DurableTask.Netherite/PartitionState/OutboxState.cs
- src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
- src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/StorageOperations.cs
- src/DurableTask.Netherite/StorageProviders/Faster/CheckpointInjector.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterAlt.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
- src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
- src/DurableTask.Netherite/StorageProviders/Faster/TrackedObjectStore.cs
- test/DurableTask.Netherite.Tests/FasterPartitionTests.cs
- test/DurableTask.Netherite.Tests/ScenarioTests.cs
Implements the decision heuristics and the state machine for periodically compacting the FASTER log.
Also includes a checkpoint injection mechanism (a new test hook called CheckpointInjector) 
and some tests that allow testing of the checkpoint/compaction state machine.
> Implement FASTER compaction and checkpoint testing mechanism

- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/OrchestrationService/Client.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
- test/DurableTask.Netherite.Tests/TestOrchestrationClient.cs
- test/LoadGeneratorApp/LoadGeneratorApp.csproj
- test/PerformanceTests/Common/Ping.cs
- test/PerformanceTests/PerformanceTests.csproj
Update to latest version of the durable extension.
> Update to 2.6.1

- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
- src/DurableTask.Netherite/OrchestrationService/OrchestrationMessageBatch.cs
- src/DurableTask.Netherite/OrchestrationService/OrchestrationWorkItem.cs
- src/DurableTask.Netherite/OrchestrationService/Partition.cs
- src/DurableTask.Netherite/PartitionState/HistoryState.cs
Custom status did not get properly persisted because it is not part of the history.
> Fix bug in persisting custom status

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/StorageProviders/Faster/AzureBlobs/BlobManager.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
Update to latest preview version.
> update to FASTER v2.0.0-preview1.3

- src/DurableTask.Netherite/Events/PartitionEvents/External/FromClients/ClientRequestEventWithQuery.cs
- src/DurableTask.Netherite/PartitionState/QueriesState.cs
- src/DurableTask.Netherite/StorageProviders/Faster/CacheDebugger.cs
- src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
Previously, unhandled exceptions left the request pending.
> Fix exception handling in queries

- src/DurableTask.Netherite/StorageProviders/Faster/StoreWorker.cs
- src/DurableTask.Netherite/TransportProviders/EventHubs/LoadMonitorSender.cs
Position publishing to the LoadMonitor must wait for persistence, otherwise progress may be lost under failures.
> Fix position publishing

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/StorageProviders/Faster/FasterKV.cs
update to FASTER v2.0.0 and move to the first non-preview release 1.0.0 (without the rc suffix)
> Drop preview status and move to 1.0.0

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
Faster 2.0.0 was immediately followed by a patch 2.0.1. This PR updates to that patch.
> Update to faster 2.0.1

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
> Create a patch release 1.0.1

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
update to latest version of FASTER.
> update to FASTER 2.0.2

- azure-pipelines-release.yml
- azure-pipelines.yml
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
This PR includes the following changes:
- adding a release pipeline yaml that creates an SBOM (Software Bill of Materials)
- updating .csproj files to include the SBOM in the NuGet package
- updating the VM to the 1ES Hosted VM
> Add Release Pipeline

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
release another patch with small fixes.
> release 1.0.2 patch

- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
- test/DurableTask.Netherite.Tests/DurableTask.Netherite.Tests.csproj
- test/LoadGeneratorApp/LoadGeneratorApp.csproj
- test/PerformanceTests/PerformanceTests.csproj
updates package dependencies for FASTER, DT, DF, and FASTER:
<PackageReference Include="Microsoft.FASTER.Core" Version="2.0.3" />     
<PackageReference Include="Microsoft.Azure.DurableTask.Core" Version="2.9.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.7.1" />
as well as a few others that are less significant, such as unit testing.
> Update package dependencies

- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs
Implements the new specialized interface `DurableTask.Core.IOrchestrationServicePurgeClient`.
Resolves #141.
> add support for specialized purge interface 

- DurableTask.Netherite.sln
- samples/HelloDTFx/HelloDTFx/HelloCities.cs
- samples/HelloDTFx/HelloDTFx/HelloDTFx.csproj
- samples/HelloDTFx/HelloDTFx/Program.cs
- src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationServiceSettings.cs
- src/DurableTask.Netherite/OrchestrationService/TransportConnectionString.cs
Adding a sample that shows how to use Netherite with just the Durable Task Framework.
> Add a sample for running an orchestration with DTFx.

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
> update to FASTER 2.0.14

- src/DurableTask.Netherite.AzureFunctions/NetheriteProviderStartup.cs
Updating NetheriteProviderStartup to implement IWebJobsStartup instead of FunctionsStartup
> Updating NetheriteProviderStartup to implement IWebJobsStartup

- samples/HelloDTFx/HelloDTFx/HelloDTFx.csproj
- samples/Hello_Netherite_with_DotNetCore/Hello.csproj
- samples/Hello_Netherite_with_Python/extensions.csproj
- samples/Hello_Netherite_with_TypeScript/extensions.csproj
Updates the version to the latest Netherite on latest v3 functions runtime. 
I tested all samples using func-cli 3, Python 3.8 and NodeJS 14.
> update Netherite version to 1.1.1 in all samples

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/DurableTask.Netherite/OrchestrationService/PartitionErrorHandler.cs
- src/DurableTask.Netherite/Scaling/AzureBlobLoadPublisher.cs
- src/DurableTask.Netherite/Scaling/AzureTableLoadPublisher.cs
- src/DurableTask.Netherite/StorageLayer/Faster/FasterStorageProvider.cs
- src/DurableTask.Netherite/TransportLayer/SingleHost/PartitionQueue.cs
- test/DurableTask.Netherite.Tests/ConcurrentTestsFaster.cs
- test/DurableTask.Netherite.Tests/ConcurrentTestsMemory.cs
- test/DurableTask.Netherite.Tests/LoadPublisherTests.cs
- test/DurableTask.Netherite.Tests/ScenarioTests.cs
This PR replaces the Azure Table Storage client SDK (v11) with the latest version (v12).
> Update to latest Azure Storage Tables client

- test/PerformanceTests/series/hello5-essentials.ps1
- test/PerformanceTests/series/runmany.ps1
Adds a hello5-essentials.ps1 series (used for the numbers in the GA announcement), and fixes a bug in the determination of the portion size.
> udpate deployment scripts for hello5 benchmarks

- src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobManager.cs
As described in #234, FASTER may fail to recover if the number of segments that fit into the memory changes. To avoid this, this PR changes the code so we treat the memory size parameter as an immutable parameter that cannot be changed after a task hub is created. 
To force immutability of this parameter, we use the same mechanism we added in #230, which means we record the memory size parameter inside the taskhubparameters.json file, and then always use that value.
Also, since memory size cannot be changed, we now use a large value (29 bits) for the default. The expectation is that it should not matter that this is larger than what should be reserved in resource-constrained environments, since the number of pages loaded into memory is generally much smaller than this maximum size (by …
> Fix recovery failures caused by changing FASTER's memory size parameter

- src/DurableTask.Netherite/PartitionState/StatsState.cs
As observed in #236, there appears to be a bug that causes the instance count to be incorrect.
The bug itself is not that dangerous, but the crashes caused by the assertion violations are (they can bring the orchestration service down without being able to recover).
This PR is a first step towards solving this issue:
- it turns the harmful crashes into benign warnings which should mitigate the impact of this issue
- the warnings contain the necessary details for us to troubleshoot the root cause more easily in the future
> Fix instance count assertion crashes

- src/DurableTask.Netherite/PartitionState/ReassemblyState.cs
Fixes `NullReferenceException` being thrown when a fragment arrives for a group that has already been removed because it expired.
> fix handling of expired groups in ReassemblyState

- src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs
- src/DurableTask.Netherite/TransportLayer/EventHubs/LoadMonitorProcessor.cs
Two bugs to fix:
- null reference in load monitor
- incorrect position of update statement means it does not work when loop is empty
> fix bugs from PR #302

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs
> update version to 1.4.1

- src/DurableTask.Netherite/DurableTask.Netherite.csproj
updates to the latest minor version of FASTER for the same major version.
> update to FASTER v2.0.23

- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs
As in title, routine PR for upcoming release.
> Rev version to 1.4.2

- src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/AzureStorageDevice.cs
- src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobEntry.cs
- src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/StorageOperations.cs
* fix hanging blob creation
* remove unnecessary try-catch
> Fix hanging blob creation (#351)

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs
Update version of all packages, and in the README.
> update version to 1.5.0

- README.md
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Properties/AssemblyInfo.cs
In preparation of releasing v1.5.0 which contains the latest FASTER.
> update to v1.5.0

- samples/Hello_Netherite_with_DotNetCore/HelloDF.csproj
- src/DurableTask.Netherite.AzureFunctions/DurableTask.Netherite.AzureFunctions.csproj
- src/DurableTask.Netherite/DurableTask.Netherite.csproj
- src/Functions.Worker.Extensions.DurableTask.Netherite/Functions.Worker.Extensions.DurableTask.Netherite.csproj
- test/DurableTask.Netherite.AzureFunctions.Tests/DurableTask.Netherite.AzureFunctions.Tests.csproj
- test/LoadGeneratorApp/LoadGeneratorApp.csproj
- test/PerformanceTests/PerformanceTests.csproj
As titled. 
Microsoft.Azure.WebJobs.Extensions.DurableTask 22.13.1 -> 2.13.2
Microsoft.Azure.DurableTask.Core  2.16.1 -> 2.16.2
Also increase Netherite patch version from 1.15.0 -> 1.15.1 for next release.
> Update Durable Dependencies to Latest Version

- test/DurableTask.Netherite.AzureFunctions.Tests/CoreScenarios.cs
- test/DurableTask.Netherite.AzureFunctions.Tests/IntegrationTestBase.cs
Initial integration tests for Durable Entities.
> Add initial integration tests for Durable Entities.

- src/DurableTask.Netherite.AzureFunctions/NetheriteProviderFactory.cs
- src/common.props
Needed for DI to actually be able to construct the type. Missed this in my original PR
> Make UnambiguousNetheriteProviderFactory constructor public

- src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
Since we moved to a newer version of FASTER we can now use a more efficient version of the compaction algorithm.
In our experiments this showed dramatic reductions in time, memory, and I/O consumption.
> Use lookup algorithm for compaction 

- src/DurableTask.Netherite/StorageLayer/Faster/FasterKV.cs
This PR addresses a problem we observed in some of the long-running tests.
The problem is that the minimal log size (as estimated based on the number of instances) seems to be different than the actual minimal log size (as a result of full compaction without any other updates). This means that compaction is continuously triggered.
We don't as of yet have an explanation, but as a defensive measure, this PR observes the discrepancy (i.e. a compaction being triggered that has zero effect) and prevents the infinite loop.
> Implement defensive measure against compaction loops

- src/common.props
As in title, routine release PR
> Rev version to 1.5.4

- .github/workflows/codeQL.yml
As in title, part of 1ES migration. Should CodeQL requirement
> Add codeQL GH action

- README.md
- src/common.props
as in title. To be merged after https://github.com/microsoft/durabletask-netherite/pull/435 is merged.
> bump minor version to 2.1.0

- azure-pipelines.yml
- samples/Hello_Netherite_with_TypeScript/package-lock.json
- samples/Hello_Netherite_with_TypeScript/package.json
- test/DurableTask.Netherite.Tests/HostFixture.cs
Updates axios in the Node sample for netherite to 1.10.0
> Update node sample deps
